// Generated by CoffeeScript 1.6.3
(function() {
  var height, line, margin, parseDate, svg, width, x, xAxis, y, yAxis;

  margin = {
    top: 20,
    right: 20,
    bottom: 30,
    left: 50
  };

  width = 960 - margin.left - margin.right;

  height = 500 - margin.top - margin.bottom;

  svg = d3.select("body").append("svg").attr("width", width + margin.left + margin.right).attr("height", height + margin.top + margin.bottom).append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  x = d3.time.scale().range([0, width]);

  y = d3.scale.linear().range([height, 0]);

  xAxis = d3.svg.axis().scale(x).orient("bottom");

  yAxis = d3.svg.axis().scale(y).orient("left");

  line = d3.svg.line().x(function(d) {
    return x(d.date);
  }).y(function(d) {
    return y(d.close);
  });

  parseDate = d3.time.format("%Y-%m-%d").parse;

  d3.csv("tsla.csv", function(error, data) {
    var max_close, max_volume, scaleVolume;
    data.forEach(function(d) {
      d.date = parseDate(d.Date);
      d.close = +d.Close;
      return d.volume = +d.Volume;
    });
    x.domain(d3.extent(data, function(d) {
      return d.date;
    }));
    y.domain(d3.extent(data, function(d) {
      return d.close;
    }));
    svg.append("g").attr("class", "x axis").attr("transform", "translate(0," + height + ")").call(xAxis);
    svg.append("g").attr("class", "y axis").call(yAxis).append("text").attr("transform", "rotate(-90)").attr("y", 6).attr("dy", ".71em").attr("fill", "white").style("text-anchor", "end").text("Price ($)").style("fill", "black");
    svg.append("path").datum(data).attr("class", "line").attr("d", line);
    max_volume = d3.max(data, function(d) {
      return d.volume;
    });
    max_close = d3.max(data, function(d) {
      return d.close;
    });
    scaleVolume = function(value) {
      return (value / max_volume) * max_close;
    };
    return svg.selectAll(".bar").data(data).enter().append("rect").attr("class", "bar").attr("x", function(d) {
      return x(d.date);
    }).attr("width", 1).attr("y", function(d) {
      return y(scaleVolume(d.volume));
    }).attr("height", function(d) {
      return height - y(scaleVolume(d.volume));
    });
  });

}).call(this);
