// Generated by CoffeeScript 1.6.3
(function() {
  var color, force, height, svg, width;

  width = 1200;

  height = 900;

  svg = d3.select("body").append("svg").attr("width", width).attr("height", height);

  color = d3.scale.category10();

  force = d3.layout.force().charge(-120).linkDistance(30).size([width, height]);

  d3.json("data.json", function(error, graph) {
    var link, node;
    force.nodes(graph.nodes).links(graph.links).start();
    link = svg.selectAll(".link").data(graph.links).enter().append("line").attr("class", "link").style("stroke-width", function(d) {
      return Math.sqrt(d.value);
    }).style("stroke", "#999").style("stroke-opacity", ".6");
    node = svg.selectAll(".node").data(graph.nodes).enter().append("circle").attr("class", "node").attr("r", 5).style("fill", function(d) {
      return color(d.group);
    }).style("stroke", "#fff").style("stroke-width", "1px").call(force.drag);
    node.append("title").text(function(d) {
      return d.name;
    });
    return force.on("tick", function() {
      link.attr("x1", function(d) {
        return d.source.x;
      }).attr("y1", function(d) {
        return d.source.y;
      }).attr("x2", function(d) {
        return d.target.x;
      }).attr("y2", function(d) {
        return d.target.y;
      });
      return node.attr("cx", function(d) {
        return d.x;
      }).attr("cy", function(d) {
        return d.y;
      });
    });
  });

  $(function() {
    return $("#slider-range-min").slider({
      range: "min",
      value: -120,
      min: -500,
      max: 0,
      slide: function(event, ui) {
        force.charge(ui.value);
        return force.start();
      }
    });
  });

  $(function() {
    return $("#slider-range-min2").slider({
      range: "min",
      value: 30,
      min: 1,
      max: 1000,
      slide: function(event, ui) {
        force.linkDistance(ui.value);
        return force.start();
      }
    });
  });

  $(function() {
    return $("#slider-range-min3").slider({
      range: "min",
      value: 0.1,
      min: 0.1,
      max: 10,
      slide: function(event, ui) {
        force.gravity(ui.value);
        return force.start();
      }
    });
  });

}).call(this);
